language: node_js
node_js:
  - "10"
# Only build tags
if: tag IS present
script:
  - npm run test-coverage
deploy:
  provider: npm
  email: "zsimo30@gmail.com"
  api_key: $NPM_TOKEN
  on:
    tags: true