language: node_js
node_js:
  - "10"
branches:
  only:
  - master
# Only build tags
if: tag IS present
script:
  - npm run test
deploy:
  provider: npm
  email: "zsimo30@gmail.com"
  api_token: $NPM_TOKEN
  on:
    tags: true